CC = g++
TARGET = prj1
OBJS = household_graph.h household_graph.cpp school_data.h school_data.cpp school.h school.cpp menu_controller.h menu_controller.cpp main.cpp 
all:
#	$(CC) -o $(TARGET) $(OBJS) -g
	$(CC) -o $(TARGET) $(OBJS) -Wall -g
