CC = g++
TARGET = song
#OBJS = string.cpp song_entry.cpp song_graph.cpp song_player.cpp
OBJS = string.cpp song_entry.cpp song_player.cpp song_table.cpp 
#OBJS = sclass.cpp student.cpp
#OBJS = course_lll.cpp bclass.cpp
all:
	$(CC) -o $(TARGET) $(OBJS) -g
